Feat(94): Sass to tailwind refactor
mento-protocol/governance-ui pull request #101
Opened 2024-03-27 18:22 UTC by RyRy79261

## Overview

This PR removes all scss styling to make use of tailwind exclusively

## Related tickets

- closes #94

2024-04-09 11:07 UTC, chapati23 reviewed
great work! didn't review all the code in-depth as it's just too much, but found a couple small issues in the styling I think

2024-04-09 11:07 UTC, chapati23 commented on src/components/contract-params/contract-params.component.tsx
>      <Expandable
Would use either a text-wrap or horizontal scrolling on mobile, currently cut off 
<img width="472" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/54e2532f-66a6-4d88-b386-2bed6bf018e5">

2024-04-09 11:07 UTC, chapati23 commented on src/components/proposals-list/proposals-list.component.tsx
> +export const ProposalsListComponent = ({ className }: ProposalsListProps) => {
weird box-shadow artefact on mobile
<img width="466" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/c4701c6d-f20f-472e-8db1-58639fe15b88">

2024-04-09 11:07 UTC, chapati23 commented on src/lib/constants/links.ts
> +  discord: "https://discord.com/invite/Zszgng9NdF",
do we want to use chat.mento.org? saw that used in the past a few times

2024-04-09 11:16 UTC, RyRy79261 commented on src/components/contract-params/contract-params.component.tsx
>      <Expandable
So Mobile still needs some polish, aiming to do mobile after the create flow is in since it affects the cards components

2024-04-09 11:17 UTC, RyRy79261 commented on src/lib/constants/links.ts
> +  discord: "https://discord.com/invite/Zszgng9NdF",
I dont have enough context to evaluate that option

2024-04-09 11:17 UTC, RyRy79261 commented on src/components/_shared/disconnect-button.tsx
> +    // <ClientOnly>
Stray comment, will remove

2024-04-09 11:39 UTC, RyRy79261 commented on src/components/_shared/block-explorer-link/block-explorer-link.component.tsx
> +      // TODO: offset set to 0.25em
@chapati23 So the offset here potentially will change as Design has updated to theme units of 8. The idea is that after the proposals ticket has completed overhauling the last components, then the TODOs can be worked through for final polish

2024-04-09 11:58 UTC, RyRy79261 commented on src/components/contract-params/contract-params.component.tsx
>      <Expandable
Fixed the trim for mobile

2024-04-09 12:01 UTC, RyRy79261 commented on src/components/proposals-list/proposals-list.component.tsx
> +export const ProposalsListComponent = ({ className }: ProposalsListProps) => {
A lot of the grid needs to be updated on mobile after the proposals are complete. the pagination also needs to be added

2024-04-09 12:09 UTC, chapati23 commented on src/lib/constants/links.ts
> +  discord: "https://discord.com/invite/Zszgng9NdF",
not important enough to block merge imo, resolving

2024-04-09 12:17 UTC, chapati23 commented on src/components/_shared/block-explorer-link/block-explorer-link.component.tsx
> +      // TODO: offset set to 0.25em
aight, was just checking if it's a leftover that could go

2024-04-09 12:21 UTC, chapati23 commented on src/app/(routes)/page.tsx
> +        &nbsp;{chain?.name}&nbsp;{chain?.testnet ? "Testnet" : "Mainnet"}
This introduces a new issue, following states are now there:

1. [Connected to CELO]  "Celo Mainnet" with a Celo Icon ✅
2. [Connected to Alfajores] "Alfajores Testnet" with a Celo Icon ✅
3. [Disconnected] " Mainnet" with a Celo Icon ❌

The last state feels off, IMO it should probably also be "Celo Mainnet" as the fallback, wdyt?

2024-04-09 14:14 UTC, chapati23 approved these changes
🔥🔥🔥

2024-04-09 22:45 UTC, bayological requested changes
There are some small things here that I noticed are off, I've showed @denviljclarke

2024-04-11 22:38 UTC, bayological approved these changes

2024-04-11 22:39 UTC, merged