Feat(107): Participants section
mento-protocol/governance-ui pull request #113
Opened 2024-04-19 12:15 UTC by RyRy79261

## Overview

This PR implements a scroll area component from Shadcn and fixes some styling inconsistencies

## Review guide

It's tricky to test this out however in implementing I loaded a bunch of dummy elements into the participants section element

## Related PR 

- closes #107

2024-04-22 18:47 UTC, denviljclarke commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +            <a
nit - Lets use next Link

2024-04-22 18:50 UTC, denviljclarke commented on src/components/_shared/progress-bar/progress-bar.component.tsx
> +      {/* <div className="flex h-4 w-full overflow-hidden rounded-3xl  border-[0.5px] border-solid border-black dark:border-gray"> */}
Do we still need this?

2024-04-22 18:52 UTC, denviljclarke commented on src/components/proposal-current-votes/proposal-current-votes.component.tsx
> +                )}
nit - extra div in this file line 155

2024-04-22 19:17 UTC, denviljclarke commented on src/styles/brand.scss
> +  // "p2-1 text-sm font-semibold text-error-dark"
what's left to do before we can kill these scss files?

2024-04-22 19:19 UTC, denviljclarke commented on src/components/proposal-current-votes/proposal-current-votes.component.tsx
> +                  <CrossMarkIcon />
invert colors in dark mode

2024-04-22 19:20 UTC, denviljclarke commented on src/components/proposal-current-votes/proposal-current-votes.component.tsx
> +                      <>Quorum reached.</>
nit - remove period after reached

2024-04-22 19:20 UTC, denviljclarke requested changes
Good work! Everything looks good, I left a few small style related comments

2024-04-23 07:25 UTC, RyRy79261 commented on src/components/proposal-current-votes/proposal-current-votes.component.tsx
> +                      <>Quorum reached.</>
@denviljclarke Where is the the confirmed behaviour?

2024-04-23 07:27 UTC, RyRy79261 commented on src/components/proposal-current-votes/proposal-current-votes.component.tsx
> +                  <CrossMarkIcon />
Is this confirmed? It looked like it worked in dark mode

2024-04-23 10:41 UTC, nvtaveras approved these changes
LGTM functionality wise, not a frontend expert so won't comment on the implementation details, although I noticed that there were some changes unrelated to the ticket which would be good to keep separate in in the future when possible.

Also curious if you tested it with a proposal with lots of votes in the different sections?

2024-04-23 16:12 UTC, RyRy79261 commented
@nvtaveras So I tested with a 50/50 `for` & `against` and the abstain is just the blank area presently

2024-04-26 00:55 UTC, denviljclarke approved these changes
LGTM

2024-04-26 00:56 UTC, merged