Create Proposal - Improved messaging about requirements
mento-protocol/governance-ui pull request #141
Opened 2024-05-16 12:04 UTC by RyRy79261

## Description

This PR improves the insight the form provides regarding the balance information and outstanding tokens needing to be locked or purchased 

## Related tickets

- closes #391 - General

2024-05-21 16:03 UTC, philbow61 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +        direction = WalletStepEnum.buyMento;
not sure if its just a placeholder but the mento web app won't be selling Mento tokens

2024-05-21 16:03 UTC, philbow61 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +    const targetVeMento = parseUnits("2500", veMentoBalance.decimals);
target VeMento should be 10.000

2024-05-22 11:04 UTC, RyRy79261 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +    const targetVeMento = parseUnits("2500", veMentoBalance.decimals);
Outdated

2024-05-22 11:04 UTC, RyRy79261 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +        direction = WalletStepEnum.buyMento;
This was based on the designs, @olenovyk to confirm

2024-05-22 11:04 UTC, RyRy79261 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
>              To create new governance proposal you need to lock 2,500 MENTO.
Outdated

2024-05-22 13:53 UTC, philbow61 approved these changes

2024-05-22 13:53 UTC, philbow61 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +        direction = WalletStepEnum.buyMento;
I would suggest removing this since the case is commented out.

2024-05-22 14:58 UTC, bowd requested changes
I'd get rid of the whole buyMento section and just have the lockMento because I think we're optimising for a very specific edge case here and it's a bit crazy. It's fine to say ok veMENTO < threshold then push the users to the lock page, and there they realise that they don't have any MENTO to lock they will need to figure out how to get mento, and will google where to get mento. It's fine 😂

2024-05-22 14:59 UTC, RyRy79261 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +  buyMento = "buyMento", // No purchasing available
@bowd Please reconfirm with @olenovyk As we discussed this again an hour ago

2024-05-22 15:00 UTC, RyRy79261 commented on src/components/create-proposal/create-proposal-wallet-step/create-proposal-wallet-step.component.tsx
> +  veMentoOutstanding: bigint;
They're used in figuring out the state, will remove once we figure out who has final say on how this works

2024-05-22 15:01 UTC, bowd approved these changes

2024-05-22 15:15 UTC, merged