Fix(165): Participants percentage
mento-protocol/governance-ui pull request #170
Opened 2024-06-06 12:41 UTC by RyRy79261

## Description

This PR fixes the percentage calculation in the participant section as well as adds Abstain, to the voting indicator bars

## Related issues

- closes #165 
- closes #169

2024-06-07 11:28 UTC, chapati23 requested changes
same issue here, can't navigate to proposal details page i.e. https://governance-k1ebo4d11-mentolabs.vercel.app/proposals/76852543598626010309184355681141482743859825585547539168614458156040950326608

regardless of wallet connected/disconnected I always get console errors

<img width="437" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/aa16d6f4-c761-426d-9f6d-43b558bd2d50">

2024-06-09 15:10 UTC, denviljclarke commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
Sometimes this doesn't add up to 100%

http://localhost:3000/proposals/82815049005223249369267239582287945782658271640355079075142781978263042166954

& 

http://localhost:3000/proposals/104083448305537669896457683783159222014868105836664782870518099656159827114092

2024-06-09 15:12 UTC, denviljclarke commented
Nice one. Left a comment about vote percentages. Looks good otherwise 👍

2024-06-10 07:27 UTC, RyRy79261 commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
What values are being used?

2024-06-10 07:28 UTC, RyRy79261 commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
This line is checking if the total is above zero though

2024-06-10 08:08 UTC, RyRy79261 commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
This function gets a percentage of a given value.

2024-06-10 08:32 UTC, chapati23 commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
he's right, this one has 52% FOR and 47% AGAINST = 99% in total https://governance-5yck8hqr3-mentolabs.vercel.app/proposals/82815049005223249369267239582287945782658271640355079075142781978263042166954

2024-06-10 09:40 UTC, RyRy79261 commented on src/components/votes-list/votes-list.component.tsx
> +  if (totalVotes > 0n) {
Was a rounding error, scaling for resulting percentage to have mantissa values fixed it.

2024-06-10 10:12 UTC, philbow61 approved these changes

2024-06-10 10:14 UTC, bayological approved these changes

2024-06-10 10:17 UTC, merged