feat: update extend lock feature to mange lock enabling updating lock…
mento-protocol/governance-ui pull request #231
Opened 2024-10-22 14:59 UTC by denviljclarke

…ed amount + refactor

### Description

Add a manage locks feature, allowing users to update the locked amount. We also disable lock management for users with multiple locks with messaging letting them know they should why they can't use this feature.

### Other changes

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #218

2024-10-28 10:01 UTC, Andrew718PLTS requested changes

2024-10-29 02:53 UTC, denviljclarke commented on src/lib/helpers/locking.ts
> +    if (lockTime === undefined || lockSlope === undefined) {
if lock time or slope is 0, it would return true, but we want to know if locktime is undefined explicitly

2024-10-29 03:03 UTC, denviljclarke commented on src/lib/hooks/useLockInfo.ts
> +    const weeksPassed = Number(currentLockingWeek) - lock?.time;
it's returned as bigint, so we need to parse to to number here

2024-10-29 12:34 UTC, Andrew718PLTS commented on src/lib/helpers/locking.ts
> +    if (lockTime === undefined || lockSlope === undefined) {
Okay, I thought you were depending on any false value

2024-10-30 09:30 UTC, baroooo requested changes
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/ac7b1a7c-21f9-4a40-84f9-1d2108d34a78">

- veMento amount is formatted with a comma, mento amount is not
- the lock expiration date looks wrong, the account that I use had a single active lock which shows 2023 (account:0xd968896991d5903613E9A83587FfFc7c8a046ffe)

when managing the lock,
- I tried to re-lock with extra amount, it failed with insufficient allowance multiple times, then it worked
- when re-locked with extra amount, it just relocked with 52 weeks of slope. it did not take my week selection into account.
- the lock that was relocked was not the active lock I had(0xf), but it was an inactive lock(0x15). because of this, now I have two active locks with this account
- if there is no withdrawable amount, the manage relock button is disabled

2024-10-30 15:13 UTC, Andrew718PLTS commented on src/components/lock-manage-lock/manage-lock.provider.tsx
> +  if (context === undefined) {
What is output of comment here? You have to check for undefined explicitly or not? If not, you can just simplify it for any negative value.

2024-10-30 15:16 UTC, Andrew718PLTS commented on src/components/lock-manage-lock/manage-lock.provider.tsx
> +    if (!needsApproval) {
What is output of comment here? You still can make it easier as you've done upper lines (here is only one line per each condition block).

2024-10-30 15:19 UTC, Andrew718PLTS requested changes

2024-10-30 15:19 UTC, Andrew718PLTS commented on src/components/lock-manage-lock/hooks/useManageLockLogic.ts
> +      if (!needsApproval) {
What is output of comment here? You still can make it easier as you've done upper lines (here is only one line per each condition block).

(It's previous comment but in another place becuase you edited the file)

2024-10-30 15:33 UTC, Andrew718PLTS commented on src/components/lock-manage-lock/manage-lock.provider.tsx
> +  if (context === undefined) {
Basically, if we would get here something else (any negatives) we can miss case - !context we just cover more cases.

2024-10-30 15:38 UTC, denviljclarke commented on src/components/lock-manage-lock/manage-lock.provider.tsx
> +  if (context === undefined) {
it can only be undefined or valid context

2024-10-30 15:43 UTC, denviljclarke commented on src/components/lock-manage-lock/hooks/useManageLockLogic.ts
> +      if (!needsApproval) {
Above we're just resolving some status, however here we're calling functions so I think it's better if you can see what's happening at a glance in different blocks

2024-10-30 16:17 UTC, Andrew718PLTS approved these changes
Approved, there are some conflicts - check this out please

2024-11-04 10:40 UTC, baroooo requested changes
- I still can not click on the manage lock for some addresses
- The address I use to test(0x4980439b9fa3c5ca0e2ece677ee0ea39d34cc75e) shows a wrong expiration time. It has a single lock with 104 weeks of slope which was locked on May 22nd but the expiration shows 26/11/2025
- I relocked this lock but the expiration time did not change. I assume it does not take the relocks into account
- I tried to relock it again, it reverts with `Arithmetic operation resulted in underflow or overflow.`

2024-11-04 13:20 UTC, denviljclarke commented
> * I still can not click on the manage lock for some addresses
> * The address I use to test(0x4980439b9fa3c5ca0e2ece677ee0ea39d34cc75e) shows a wrong expiration time. It has a single lock with 104 weeks of slope which was locked on May 22nd but the expiration shows 26/11/2025
> * I relocked this lock but the expiration time did not change. I assume it does not take the relocks into account
> * I tried to relock it again, it reverts with `Arithmetic operation resulted in underflow or overflow.`

1. Those addresses have multiple locks, so they shouldn't be managed in the UI.
2. I just simplified the expiration date calculation
3 & 4 are related to the subgraph not updating in timely manner, as I mentioned on Discord, it takes 10 > mins sometimes

2024-11-05 10:04 UTC, baroooo reviewed
all the numbers look correct ✅ 
one thing I noticed was when I relocked with some extra amount, the UI shows insufficient approval error but the txs still go through.
it happened for this account: 0x86cC009F2958f7e856B5BcC2a67e7DD5C4dB4F6f I withdrew first and then relocked with 2000

2024-11-08 10:20 UTC, baroooo approved these changes
LGTM ✅

2024-11-08 15:25 UTC, merged