feat(governance-ui#35): Add proper data for Contract params on homepage
mento-protocol/governance-ui pull request #43
Opened 2024-01-23 10:06 UTC by tplocic20

### Description

Add a proper calculation of data for contract params view

### Other changes

n/a

### Tested

PR build and lint successful

### Related issues

- Fixes #35 

### Backwards compatibility

n/a

### Documentation

n/a

2024-01-24 11:09 UTC, AnnaJ-P11 commented on app/components/proposal-summary/proposal-summary.component.tsx
> +  console.log(contractData);
console

2024-01-24 11:09 UTC, AnnaJ-P11 commented on app/components/proposal-summary/proposal-summary.component.tsx
> +    console.log(proposals.map((proposal) => proposal.endBlock));
console

2024-01-24 15:15 UTC, AnnaJ-P11 approved these changes

2024-01-25 20:37 UTC, nvtaveras reviewed
Left a few comments but it's my first time reviewing anything related to the governance ui, so take them with a grain of salt 🙃

2024-01-25 20:37 UTC, nvtaveras commented on app/helpers/contracts.ts
> +export const lockingContract = "0xc1d32e3bac67b28d31d7828c8ff160e44c37be1c";
do we want to separate these by network?

2024-01-25 20:37 UTC, nvtaveras commented on app/components/proposals-list/proposals-list.component.tsx
> +    deadlineAt: addDays(new Date(), 14),
Is this temporary? Since I assume `deadlineAt` would depend on other parameters of the proposal like `state` or `endBlock`?

2024-01-25 20:37 UTC, nvtaveras commented on app/interfaces/proposal.interface.ts
> +  endBlock: BigInt | string;
is `string` needed here?

2024-01-29 22:38 UTC, bayological commented on app/helpers/contracts.ts
> +export const lockingContract = "0xc1d32e3bac67b28d31d7828c8ff160e44c37be1c";
+1 on @nvtaveras comment. This is not the best way forward. We should refactor the useChainState hook to also expose the contract addresses for the connected network.

2024-01-29 23:44 UTC, bayological commented on app/helpers/contracts.ts
> +export const lockingContract = "0xc1d32e3bac67b28d31d7828c8ff160e44c37be1c";
I've created this issue for this; we will clean this up in the next sprint. https://github.com/mento-protocol/governance-ui/issues/49

2024-01-30 08:22 UTC, bowd commented on app/helpers/contracts.ts
> +export const lockingContract = "0xc1d32e3bac67b28d31d7828c8ff160e44c37be1c";
👍 I have a draft of this locally that I didn't push so we can leave this as is and I can pick up #49

2024-01-30 10:50 UTC, bowd requested changes

2024-01-30 10:50 UTC, bowd commented on package-lock.json
When I added graphql and all that I moved to `pnpm` because `npm` didn't work for me when referencing the rainbowkit beta dependency. But after updating to latest `node` and `npm` versions it works. So I am happy to go back to using pure `npm` but if so lets remove the `pnpm-lock.yaml` file as well.

2024-02-01 08:46 UTC, tplocic20 commented on app/components/proposals-list/proposals-list.component.tsx
> +    deadlineAt: addDays(new Date(), 14),
I would prefer to remove it

2024-02-01 09:56 UTC, tplocic20 commented on app/components/proposal-summary/proposal-summary.component.tsx
> +  }));
I'll drop those maps and interfaces.
Let's have one source of truth

2024-02-02 17:09 UTC, bayological requested changes
@tplocic20 I don't think we're there yet. Were you able to get the correct total veMento displayed in the UI?

I changed the locking contract address to [0x65a1271ce7B2ec8D564A4Bc752E13A36a46e81B8](https://github.com/mento-protocol/mento-sdk/blob/05a824308d35da9467fcfd698c3ee701ac12e1b8/src/constants/addresses.ts#L21) which is correct for alfajores but I am still getting 0 as the total supply in the interface. The result of the [read contract call](https://github.com/mento-protocol/governance-ui/blob/b349e6c9d9a5994ae290f5a63299eb2a9794d30b/app/components/proposal-summary/proposal-summary.component.tsx#L13) is always undefined. 

This is not the same as what I see on [celo scan](https://alfajores.celoscan.io/address/0x65a1271ce7B2ec8D564A4Bc752E13A36a46e81B8#readProxyContract#F26):
![image](https://github.com/mento-protocol/governance-ui/assets/6872903/29d1f09d-96fb-4a66-9638-958fcd6eb816)

2024-02-05 10:51 UTC, tplocic20 commented
Fixed the total supply preview

2024-02-05 15:50 UTC, bayological approved these changes

2024-02-06 11:13 UTC, bowd approved these changes

2024-02-06 11:16 UTC, merged