Feat/19 allow users to view all proposals
mento-protocol/governance-ui pull request #45
Opened 2024-01-25 21:38 UTC by AnnaJ-P11

2024-01-26 09:18 UTC, bowd requested changes

2024-01-26 09:18 UTC, bowd commented on app/(api)/api/proposals/[id]/route.ts
> +  votes: {
We can probably remove all fo these if they are not referenced anywhere anymore.

2024-01-26 09:18 UTC, bowd commented on app/components/proposals-list/proposals-list.component.tsx
> +            <div className={styles.header}>Votes against</div>
We should add "abstain" here as well.

2024-01-26 09:18 UTC, bowd commented on app/components/proposals-list/proposals-list.component.tsx
> +                    {index + 1 <= 9 ? `0${index + 1}` : index + 1}
We should use the `proposalId` field (but not the `id` field)  instead of the array index.

2024-01-26 09:18 UTC, bowd commented on app/graphql/policies/Proposal.ts
> +        const votesAbstain = getCalculatedVotes(votesAbstainArr);
I think there's a missunderstanding here, a proposal will have only 3 entries in the `supports` field, one for each support type of support (against, for, abstain). Which already contain the total number of votes. So the `supports` field already folds aggregates. It's enough to do smth like:
```typescript
const supportToKey: Map<0 | 1 | 2, keyof Votes> = { 0: 'votesAgainst', 1: 'votesFor', 0: 'votesAbstain' }
return supports.reduce((acc, support) => {
    acc.votesTotal += support.weight;
    acc[supportToKey[support.support]] += support.weight;
    return acc
  })
}, { votesAgainst: BigInt(0), votesFor: BigInt(0), votesAbstain: BigInt(0), votesTotal: BigInt(0)})
```

(just a draft, there might be issues but you get the point)

2024-01-26 09:18 UTC, bowd commented on app/components/proposals-list/proposals-list.component.tsx
> +                  max={Number(votes.votesTotal)}
This won't work as the amount of votes is a big number for a reason. We can use https://viem.sh/docs/utilities/formatUnits to display this. The votes are in 18 decimal points so you can do `formatUnits(votes.votesTotal, 18)` here. Ofc this applies for all the above.

2024-01-26 09:57 UTC, olenovyk commented on app/components/proposals-list/proposals-list.component.tsx
> +            <div className={styles.header}>Votes against</div>
@bowd we didn't add abstain to the list of proposals on purpose. In my opinion it is not very important number. Yes/no are the important ones. Anstain usually has a tiny fraction of total votes. It will be visible on the proposal details page though. Let me know if you don't agree with that.

2024-01-29 11:35 UTC, AnnaJ-P11 commented on app/components/proposals-list/proposals-list.component.tsx
> +                    {index + 1 <= 9 ? `0${index + 1}` : index + 1}
ProposalId field is very long now, it ruins proposal list UI. Will it be shorter in the future? 
![proposaId](https://github.com/mento-protocol/governance-ui/assets/153610715/f7b75ed2-4814-4a50-8ac5-e11e618899f6)

2024-01-29 16:45 UTC, AnnaJ-P11 commented
https://github.com/mento-protocol/governance-ui/pull/19

2024-01-30 00:36 UTC, bayological commented on app/components/proposals-list/proposals-list.component.tsx
> +                    <div className={styles.index}>{proposalId}</div>
@AnnaJ-P11 Did you check this out locally? This is what I see when running locally. The same view on the [preview](https://governance-jut27hp83-mentolabs.vercel.app/)
![image](https://github.com/mento-protocol/governance-ui/assets/6872903/56b35222-c976-41b7-a6d0-ca1bb7b99328)

2024-01-30 00:38 UTC, bayological requested changes
We need to do something about the proposal ID. The actual ID is too long and breaks the UI. If the results of the get proposals query are ordered I'd propose using the index of the proposal but open to other suggestions here. @bowd @olenovyk

2024-01-30 08:14 UTC, AnnaJ-P11 commented on app/components/proposals-list/proposals-list.component.tsx
> +                    <div className={styles.index}>{proposalId}</div>
Yep, I've tested it, and I saw that proposalId is very long, so I added a commet to previous comment, and I'am wainting for the response
![image](https://github.com/mento-protocol/governance-ui/assets/153610715/4c30735b-535e-40e6-adaa-dd8a9b179426)

2024-01-31 09:06 UTC, bowd commented on app/components/proposals-list/proposals-list.component.tsx
> +                    <div className={styles.index}>{proposalId}</div>
Then let's remove this alltogether for now.

2024-01-31 09:11 UTC, bowd commented
> We need to do something about the proposal ID. The actual ID is too long and breaks the UI. If the results of the get proposals query are ordered I'd propose using the index of the proposal but open to other suggestions here. @bowd @olenovyk

I think using the index is inconsistent. It doesn't give you information. The same proposal will first get an index of `1`, and when a new proposal gets created, it will have an index of `2`, and the new one will get index `1`. That doesn't give much value or information and might lead to confusion.

I see a few options: 
1. Remove that column all together
2. Just use the first 8 characters of the ID as a sort of "shorthand" proposal id. Then it's at least unique and tied to the proposal and consistent.
3. Use a blockies type icon derived from the proposalId.

I would be happy with (1) or (2).

@bayological  / @olenovyk  / @AnnaJ-P11

2024-01-31 09:24 UTC, bowd requested changes

2024-01-31 09:24 UTC, bowd commented on app/graphql/policies/Proposal.ts
> +
I think this is no longer used.

2024-01-31 09:24 UTC, bowd commented on app/graphql/policies/Proposal.ts
> +  [key: string]: bigint;
We shouldn't ned this.

2024-01-31 09:24 UTC, bowd commented on app/graphql/policies/Proposal.ts
> +        const supportType: { [key: number]: string } = {
might help to type this as `Record<number, keyof Votes>`

2024-01-31 09:24 UTC, bowd commented on app/graphql/policies/Proposal.ts
> +        const supportsRef = readField<Array<ProposalSupport>>("supports");
I would turn this into:
```
const supportsRef = readField<Array<ProposalSupport>>("supports") || [];
```

And then remove all the `?` from later instructions, as they won't be necessary, and also you can then just return from the reduce command as you will no longer have to guard undefined anywhere.

2024-01-31 09:30 UTC, olenovyk commented
Seems like this questions is bigger than just UI. I think we need to have some sort of ID to indentify proposals. 
We should have smth like MGP-1, MGP-2, .... etc. in a way how Celo has CGP-100 or Ethereum EIP-4634. How can we achieve that? How are IDs for Ethereum proposals are created?

The long identifier wouldn't work because it's too long.

From the options that Bogdan listed, option 2 seems like it has the most sense, but I will have 4 symbols instead of 8.

2024-01-31 13:21 UTC, olenovyk commented
> > We need to do something about the proposal ID. The actual ID is too long and breaks the UI. If the results of the get proposals query are ordered I'd propose using the index of the proposal but open to other suggestions here. @bowd @olenovyk
> 
> I think using the index is inconsistent. It doesn't give you information. The same proposal will first get an index of `1`, and when a new proposal gets created, it will have an index of `2`, and the new one will get index `1`. That doesn't give much value or information and might lead to confusion.
> 
> I see a few options:
> 
> 1. Remove that column all together
> 2. Just use the first 8 characters of the ID as a sort of "shorthand" proposal id. Then it's at least unique and tied to the proposal and consistent.
> 3. Use a blockies type icon derived from the proposalId.
> 
> I would be happy with (1) or (2).
> 
> @bayological / @olenovyk / @AnnaJ-P11

let's remove this column

2024-02-02 18:47 UTC, bayological approved these changes

2024-02-06 10:56 UTC, bowd approved these changes

2024-02-06 10:57 UTC, merged