feat: update null value handling
mento-protocol/governance-ui pull request #46
Opened 2024-01-25 22:12 UTC by denviljclarke

2024-01-29 19:44 UTC, bayological requested changes

2024-01-29 19:44 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +      <Link href={blockExplorerContractUrl}>
Let's update this so the link opens in a new tab. This is a slightly better experience.

2024-01-29 19:44 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +  const timeLockControllerAbi = [
Similar to the [Governance contract abi](https://github.com/mento-protocol/governance-ui/blob/382aba2a32d88e915d92aee314e051a0a3e60156/app/abis/Governor.ts#L1) this should be a const and in a shared location so it can be easily reused across the application.

2024-01-29 19:44 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +  return new Governance(provider).getGovernorContract();
After looking at the rest of the codebase properly, this is not the best way to go. We should consistently make use of viem for interacting with the core contracts. To go in this direction, we will end up not using the SDK functions as they are tied to ethers@v5. However we should fetch the contract addresses from the SDK instead of hardcoding them.

I would refactor this to use the Governor abi that is already defined [here](https://github.com/mento-protocol/governance-ui/blob/382aba2a32d88e915d92aee314e051a0a3e60156/app/abis/Governor.ts#L1) then use the viem [readContract function](https://viem.sh/docs/contract/readContract#readcontract).

In order to retrieve the contract addresses, we'll need to update the [chain helper](https://github.com/mento-protocol/governance-ui/blob/382aba2a32d88e915d92aee314e051a0a3e60156/app/helpers/chains.ts#L4) to make use of the [contract address map](https://github.com/mento-protocol/mento-sdk/blob/05a824308d35da9467fcfd698c3ee701ac12e1b8/src/constants/addresses.ts#L4). These will then be available throughout the application.

2024-01-29 21:50 UTC, nvtaveras commented on app/components/contract-params/contract-params.component.tsx
> +  const blockExplorerUrl = connectedChainOrMainnet.blockExplorers?.default.url;
tried this in the preview while connected to Alfajores and the links were pointing to blockscout instead of celoscan

2024-01-29 21:50 UTC, nvtaveras commented on app/components/contract-params/contract-params.component.tsx
> +    length = 15;
how about calling this `addressLength` instead? also you can set it to 30 in the declaration and get rid of the `else` statement

2024-01-29 21:50 UTC, nvtaveras commented on app/components/contract-params/contract-params.component.tsx
> +  const secondsPerBlock = secondsPerWeek / blocksPerWeek;
Can get rid of all of this and just hardcode secondsPerBlock to 5

2024-01-29 21:58 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +  const blockExplorerUrl = connectedChainOrMainnet.blockExplorers?.default.url;
@nvtaveras The configured explorer wasn't set as part of these changes, but we should use celoscan instead. 

@denviljclarke They are set [here](https://github.com/mento-protocol/governance-ui/blob/382aba2a32d88e915d92aee314e051a0a3e60156/app/helpers/chains.ts#L68)

2024-01-29 23:50 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +  return new Governance(provider).getGovernorContract();
I've made a separate issue to cover pulling the addresses from the SDK here https://github.com/mento-protocol/governance-ui/issues/49
For now, I'd say we should update this code to just use the read contract function and remove the use of ethers.

2024-01-30 23:35 UTC, nvtaveras commented on app/helpers/chains.ts
> +      address: "0x65a1271ce7B2ec8D564A4Bc752E13A36a46e81B8",
We should read all of these from the SDK no? https://github.com/mento-protocol/mento-sdk/blob/05a824308d35da9467fcfd698c3ee701ac12e1b8/src/constants/addresses.ts#L14-L22

2024-01-30 23:42 UTC, denviljclarke commented on app/helpers/chains.ts
> +      address: "0x65a1271ce7B2ec8D564A4Bc752E13A36a46e81B8",
Correct, but as it's being implemented [in another issue](https://github.com/mento-protocol/governance-ui/issues/49) I made this change temporarily to partially mimic how it might look; me and @bayological will have to coordinate to update our code accordingly once the other issue is resolved.

2024-01-30 23:47 UTC, denviljclarke commented on app/components/contract-params/contract-params.component.tsx
> +  const blockExplorerUrl = connectedChainOrMainnet.blockExplorers?.default.url;
@nvtaveras I also didn't change this as it's part of the chain config in the [same issue I mentioned](https://github.com/mento-protocol/governance-ui/issues/49)

2024-01-31 20:09 UTC, denviljclarke commented
Final update on this @bayological @nvtaveras. 

1. As @olenovyk mentioned [here](https://github.com/mento-protocol/governance-ui/issues/21#issuecomment-1919297776) above, we'll display Celo information instead of an overlay
2. I've also confirmed with Baran that the formatting for the quorum need and proposal threshold values are just 10*18 which I've done but I suspect we'll need to review it in the future once we have realistic number of tokens locked & veToken supply.

2024-02-01 00:04 UTC, bayological commented on app/abis/TimelockController.ts
> +// TODO: Get full ABI
This comment can be removed. And we don't necessarily need the full ABI. It's fine only to have definitions for the functions we are using. So this can either grow organically or someone can dump the full one here.

2024-02-01 00:05 UTC, bayological approved these changes

2024-02-01 21:58 UTC, nvtaveras approved these changes

2024-02-02 06:03 UTC, merged