feat(27): Allow users to see their locks
mento-protocol/governance-ui pull request #56
Opened 2024-02-20 17:02 UTC by tplocic20

### Description

- Allows to see all locks of a connected wallet

### Tested

- You need to have an accounts with locks

### Related issues

-  Fixes #27

2024-02-21 12:50 UTC, chapati23 requested changes
nice work, couple comments

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +  console.log(data);
remove console.log

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
>  import styles from "./locks-list.module.scss";
there is a typo on the locks page itself that was missed in  past reviews

<img width="191" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/6699c890-3ade-42dd-9fd3-ca188eb851b5">

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
>  import classNames from "classnames";
again on locks page UI bug, there should be thousand separators for large numbers

current status: 
<img width="171" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/6c00cbd5-3f70-4587-9489-54dd8b393008">


should be according to design:

![Uploading image.png…]()

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
>  import classNames from "classnames";
again locks page, typo: 

- **Wrong**: You recieve veMENTO
- **Right**: You receive veMENTO

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +  const mentoParsed = useMemo(() => {
these numbers should have thousand separators as in the design

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +    return `${decimalsSplit[0]}${decimalsSplit[1] ? `.${decimalsSplit[1].slice(0, 3)}` : ""}T`;
why the 'T' postfix?

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +    return `${endDate.toLocaleDateString()} (${format(endDate, "E")})`;
why the `(Wed)` in parentheses at the end? don't see that in the design

2024-02-21 12:50 UTC, chapati23 commented on app/(routes)/my-voting-power/page.tsx
> +            {address && !isConnecting && !isDisconnected && (
you already check `!isDisconnected` on line 17

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +    const formattedAmount = formatUnits(lock.amount || 0n, 15);
why 15?

2024-02-21 12:50 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
> +    const formattedLockAmount = formatUnits(getLock?.[0] || 0n, 15);
reminder comment for the "why 15" discussion from above

2024-02-21 14:26 UTC, tplocic20 commented on app/components/locks-list/locks-list.component.tsx
>  import classNames from "classnames";
Number input does not really support formatting

2024-02-21 15:05 UTC, chapati23 commented on app/components/locks-list/locks-list.component.tsx
>  import classNames from "classnames";
you're right, it's not trivial.

found a few working snippets to self-build it, i.e. https://amiryxe.github.io/easy-number-separator/ (source code at https://github.com/amiryxe/easy-number-separator/)

it's a nice-to-have so i''ll leave it up to you if you wanna do the extra work or not, feel free to close this conversation as it shouldn't block the PR from getting merged

2024-02-23 14:12 UTC, tplocic20 commented on app/components/locks-list/locks-list.component.tsx
>  import classNames from "classnames";
We will do it when having a final decision and final designs for locking - so we will have the task to put such effort there

2024-02-23 14:14 UTC, tplocic20 commented
@chapati23 Got confused with the decimals - it's fixed now :)
And I have hidden the extending and locking options until further decisions

2024-02-23 15:40 UTC, chapati23 requested changes
didn't see any new commits here, did you push your latest changes?

2024-02-23 15:40 UTC, chapati23 commented on app/components/proposal-summary/proposal-summary.component.tsx
> +    const formattedTotalSupply = formatUnits(totalSupply || 0n, 15);
i unresolved this because i still see `15` here and didn't get any response

2024-02-26 09:00 UTC, tplocic20 commented
@chapati23 Pushed the code once more - should be there

2024-02-26 10:12 UTC, chapati23 commented on app/(routes)/my-voting-power/page.tsx
> +            {address && !isConnecting && !isDisconnected && (
@tplocic20 ping

2024-02-26 10:23 UTC, tplocic20 commented on app/components/locks-list/locks-list.component.tsx
> +    return `${endDate.toLocaleDateString()} (${format(endDate, "E")})`;
Ah, it was added just for test

2024-02-26 10:25 UTC, chapati23 approved these changes
lfg

2024-02-27 04:14 UTC, denviljclarke commented on app/components/locks-list/locks-list.component.tsx
> +      {/*<div>*/}
Should this be commented out?

2024-02-27 04:37 UTC, denviljclarke commented on app/components/locks-list/locks-list.component.tsx
> +    const res = await showConfirm(
If I'm not mistaken, based on the AC and the designs here https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=7920-16537&mode=design&t=j1SAUtoLRXNzumdI-4 when a user chooses to relock, a calendar should be displayed, Did something change?

2024-02-27 04:41 UTC, denviljclarke commented on app/(routes)/my-voting-power/page.tsx
> +      {/*<h2 className="text-2xl mt-8 mb-4">My Voting Power</h2>*/}
Should this be commented out?

2024-02-27 05:12 UTC, denviljclarke commented on app/(routes)/my-voting-power/page.tsx
> +      {!isDisconnected && (
Also, the design for this MentoLock component has been updated

2024-02-27 05:14 UTC, denviljclarke commented on app/(routes)/my-voting-power/page.tsx
> +      {/*    <MentoLock className="max-w-[428px]" />*/}
Also, [the design for this MentoLock component has been updated](https://discord.com/channels/966739027782955068/981497164817637447/1210554920844140554)

2024-02-27 05:22 UTC, denviljclarke commented on app/components/locks-list/locks-list.component.tsx
> +          onExtend();
I know it's not explicity part of the ticket but it would be good to have some kind of feedback confirming if the lock was sucessfully extended

2024-02-27 05:26 UTC, denviljclarke requested changes
I left a few comments about design changes & commented out code

2024-02-27 12:00 UTC, tplocic20 commented on app/components/locks-list/locks-list.component.tsx
> +      {/*<div>*/}
Yes, because we want to finish the locking and extending in separate tickets. It was commented to not cause any issues while the designs were still in progress

2024-02-27 12:00 UTC, tplocic20 commented on app/(routes)/my-voting-power/page.tsx
> +      {/*<h2 className="text-2xl mt-8 mb-4">My Voting Power</h2>*/}
The same case as above

2024-02-27 12:00 UTC, tplocic20 commented on app/(routes)/my-voting-power/page.tsx
> +      {/*    <MentoLock className="max-w-[428px]" />*/}
Yes, and Anna is working on it under a separate task

2024-02-27 12:39 UTC, denviljclarke approved these changes
Checked that locks were displayed. 

LGTM

2024-02-27 15:26 UTC, merged