Feat: voting on proposals
mento-protocol/governance-ui pull request #69
Opened 2024-03-05 23:30 UTC by denviljclarke

### Description

### Other changes

- Small change in validation and flows.

### Tested

Ran the locally and ensured 

### Related issues

-  Fixes #23

2024-03-06 14:19 UTC, chapati23 requested changes
nice work, voted for and against a proposal from different accounts and it all worked fine.

comments mainly on UX improvements and code structure

2024-03-06 14:19 UTC, chapati23 commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +              <span>Error casting vote</span>
why two separate spans, can't we just do

```
<span>Error casting vote: {(vote.error as BaseError).shortMessage || vote?.error?.message}</span>
```

2024-03-06 14:19 UTC, chapati23 commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +            Your vote is being processed
why can't we use a block explorer link here already? i think we should already have the TX hash returned by `useWriteContract()`

2024-03-06 14:19 UTC, chapati23 commented on app/(routes)/proposals/[id]/page.tsx
>                <Participants
i think the partial removal of the modals have triggered the closing "X" to always be present on the participants box now

<img width="418" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/b3f8b7a2-6fc0-4496-a9d2-6b8728e80dfa">

2024-03-06 14:19 UTC, chapati23 commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +          <span>{`You have already voted "${voteTypeMap[voteReceipt.support].message}" on this proposal`}</span>
can we link them to their past vote tx here?

2024-03-06 14:19 UTC, chapati23 commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +          <span>{`You have already voted "${voteTypeMap[voteReceipt.support].message}" on this proposal`}</span>
I think we should also use the same little [FOR] and [AGAINST] mini buttons you're using on the pending states. would make it visually much clearer how I voted in the past.

i.e. `"You voted [FOR] this proposal in [this transaction](link-to-block-explorer)"`

<img width="267" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/251aafe8-1122-444b-a2b6-38e3a820d999">

2024-03-06 14:32 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +          <span>{`You have already voted "${voteTypeMap[voteReceipt.support].message}" on this proposal`}</span>
Sure. It wasn't in the design, but good idea 👍

2024-03-06 14:33 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +          <span>{`You have already voted "${voteTypeMap[voteReceipt.support].message}" on this proposal`}</span>
I think so as well, this was a design choice by me, I'll correspond with @olenovyk to see how he feels about it 👌

2024-03-06 14:38 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +              <span>Error casting vote</span>
We can, it's just a design choice to have the reason message on another line, I'll let @olenovyk decide.

2024-03-06 15:58 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +      <span>Please connect your wallet to participate in the voting.</span>
I agree, I just implemented based on the designs. What do you think about this change? @olenovyk

2024-03-06 15:59 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +    } catch (error) {
It's shown below using vote.error

2024-03-06 17:09 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> -import { Button, Card } from "@/app/components/_shared";
So we're finally using the the correct font here, this is our brand font. There will surely be an issue once the design reveiw is completed (if there isn't already) to update components to use this font where required as per the design - quite a few places.

2024-03-06 19:38 UTC, denviljclarke commented on app/components/_shared/block-explorer-link/block-explorer-link.component.tsx
> +function BlockExplorerLink({ children, type, item, className }: Props) {
left over from merge conflict reconciliation

2024-03-11 13:39 UTC, olenovyk commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +      <span>Please connect your wallet to participate in the voting.</span>
makes sense to me as well.

2024-03-11 14:59 UTC, RyRy79261 reviewed
Looks good, I think we need to add `frame` to the wallet options as we're getting an RPC error

2024-03-11 15:05 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/participants.component.tsx
> +      <TabList tabs={["For", "Against", "Abstain"]}>
It would be good, however the creation of this component wasn't apart of this ticket. I just made some changes to to this file to remove some side effects caused by removing some modal functionality which wasn't apart of the designs.

2024-03-11 15:06 UTC, denviljclarke commented on .env
> -NEXT_PUBLIC_SUBGRAPH_URL=https://api.studio.thegraph.com/query/63311/mento/version/latest
yeh, it should be removed. It was added in another PR. I'll remove it now

2024-03-11 15:08 UTC, chapati23 commented on .env
> -NEXT_PUBLIC_SUBGRAPH_URL=https://api.studio.thegraph.com/query/63311/mento/version/latest
it's very unusual but next explicitly recommends it https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#default-environment-variables

<img width="666" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/8c9b2435-0bf6-4f11-bc46-8dc8d75a1789">


personally I think nextjs is setting a terrible precedent here but that's the way they want it apparently

2024-03-11 16:15 UTC, denviljclarke commented on .env
> -NEXT_PUBLIC_SUBGRAPH_URL=https://api.studio.thegraph.com/query/63311/mento/version/latest
Got it, thanks for the clarification @chapati23

2024-03-12 11:07 UTC, RyRy79261 commented on .env
> -NEXT_PUBLIC_SUBGRAPH_URL=https://api.studio.thegraph.com/query/63311/mento/version/latest
Hmmm, I think it's to align with Vercel. I guess the rational would be that nothing in a front end app should be referencing actual secrets anyway, but for quickly shutting down a front end via an environment variable rather than a pull request. 

I'll see what their prioritization is.

2024-03-12 11:08 UTC, RyRy79261 commented on app/(routes)/proposals/[id]/_components/participants.component.tsx
> +      <TabList tabs={["For", "Against", "Abstain"]}>
Ahh ok, I'll add it to my list then, thanks!

2024-03-12 11:34 UTC, RyRy79261 approved these changes

2024-03-12 14:16 UTC, denviljclarke commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +                {(vote.error as BaseError).shortMessage || vote?.error?.message}
What should be centralized?

2024-03-12 17:14 UTC, chapati23 commented on app/(routes)/proposals/[id]/_components/vote.component.tsx
> +                {(vote.error as BaseError).shortMessage || vote?.error?.message}
"Error casting vote
User rejected the request"

every other element on this component is centralized

2024-03-13 03:17 UTC, denviljclarke commented on app/hooks/useProposalStates.ts
> +    // @ts-ignore
It's also breaking the build on Vercel.

![Screenshot 2024-03-12 at 10 03 00 PM](https://github.com/mento-protocol/governance-ui/assets/60730266/c13d4a95-ac5c-4922-aaf2-ea9932b77d30)

Maybe you can have a quick look. for now, I'm going to re-add the TODO.

2024-03-13 16:44 UTC, chapati23 commented on app/hooks/useProposalStates.ts
> +    // @ts-ignore
alright, pretty sure it's some TS version issue that go introduced by a different TS version at some point, I'm fine with leaving the TODO in for now

2024-03-13 17:21 UTC, chapati23 requested changes
looks good, thanks for addressing all the comments, I know it was a lot!

just one last issue I found, probably merge conflict, there's a missing border on the cast-vote component when the proposal is already over:

<img width="459" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/43fbde7d-b5f3-448d-bc2e-6769b7d59569">

2024-03-13 17:21 UTC, chapati23 commented on app/components/vote-inactive-proposal-status-message/inactive-proposal-status-message.tsx
> +    <>
```suggestion
    <Card>
```

2024-03-13 17:21 UTC, chapati23 commented on app/components/vote-inactive-proposal-status-message/inactive-proposal-status-message.tsx
> +    </>
```suggestion
    </Card>
```

2024-03-13 17:31 UTC, merged