Feat/ve-locking component 26
mento-protocol/governance-ui pull request #70
Opened 2024-03-06 15:00 UTC by AnnaJ-P11

### Description

-change date format in Date picker
-change Date picker range - only future date can be selected and further than 2 years away from now (dates further than 2 years from now can't be selected)
-change mechanism to counting weeks, and show weeks on slider
-change slider range to:  1 week to 2 years
-add debounce to getting Lock (to prevent too many contract calls)
-add locking MENTO on contract

### Other changes

- add Toaster from lib: sonner

### Tested

Go to My Voting Power. Fill the form and click 'Lock MENTO'

### Related issues

-  Fixes #26

2024-03-06 15:42 UTC, tplocic20 requested changes
Apart for this tiny change - lgtm

2024-03-06 15:42 UTC, tplocic20 commented on app/components/_shared/mento-lock/mento-lock.component.tsx
> +    .min(new Date())
Minimum lock is 1 week. Moved to the next wednestay

2024-03-11 16:00 UTC, bayological reviewed
Some points on the design:
- The width of the input box for Mento to lock should be the same as the 'Lock until' input. 
- The font weight of the title should be 500
- The font size of the number input should be 22px, in the app it is set to 18px
- On the number input the padding should be 10px all round but in the app it is 18px on the top and bottom and 32 on the sides

Please let's double check the styling to make sure it matches up with what we have in the designs

The application:
![image](https://github.com/mento-protocol/governance-ui/assets/6872903/c87b9548-fcf7-4f3a-bafe-e1599b1c0d49)

The design:
![image](https://github.com/mento-protocol/governance-ui/assets/6872903/d159203c-4197-43ad-963c-37f9cdea960b)

2024-03-11 17:49 UTC, bayological reviewed
There's a noticeable delay when adjusting the lock period slider, where the veMento calculation briefly shows as zero before updating to the correct value. To improve user experience, implementing a loading indicator, such as a spinner, would be helpful to show that an update is in progress without showing an incorrect value. 

[Screencast from 03-11-2024 12:41:42 PM.webm](https://github.com/mento-protocol/governance-ui/assets/6872903/241cf41d-a1bb-4c9e-8e85-ddfb2582a097)

2024-03-11 17:56 UTC, bayological reviewed
Let's change this message to something that is a bit more clear. "Amount exceeds current balance" makes more sense.

![image](https://github.com/mento-protocol/governance-ui/assets/6872903/958aba23-99e8-4bb6-a56c-03f9fb6a50f8)

2024-03-11 17:59 UTC, bayological requested changes
Left some comments on design to be addressed.

2024-03-12 13:25 UTC, AnnaJ-P11 commented on app/components/_shared/mento-lock/mento-lock.component.tsx
> +    .min(new Date())
I removed that rule, it's not necessary because only next Wednesdays are possible to choose, nothing else

2024-03-13 11:17 UTC, RyRy79261 commented
After inputting the `Lock until` data, the fill collor on the left hasn't caught up with the slider at the lower values.

I also wasn't able to trigger the Lock, clicking `Lock` in the confirm alert closed the alert, not sure if this is expected.

![image](https://github.com/mento-protocol/governance-ui/assets/10461622/22116357-f15b-4f69-9251-d56f0e082508)

![image](https://github.com/mento-protocol/governance-ui/assets/10461622/5ebdd0df-b094-4735-b33c-70024fd7b757)

![image](https://github.com/mento-protocol/governance-ui/assets/10461622/29739ad3-9360-4993-825f-19bdef547fa3)

![image](https://github.com/mento-protocol/governance-ui/assets/10461622/98140769-c1dc-45a4-b84b-69402c12ef0c)

2024-03-15 11:45 UTC, AnnaJ-P11 commented
@RyRy79261 Closing the popup when you click "Lock"  is good behavior. Also clicking "Lock" button should open a popup from your wallet where you can confirm the transaction. Check your wallet please. If it still doesn't work let me know :)

2024-03-19 10:24 UTC, tplocic20 approved these changes

2024-03-19 21:52 UTC, bayological requested changes
This is not ready to be merged. When running this locally, I am unable to create a lock. As show in the video below, nothing happens after clicking the confirmation in the modal:

[Screencast from 03-19-2024 04:50:05 PM.webm](https://github.com/mento-protocol/governance-ui/assets/6872903/83e35a98-6c94-48d2-b11b-6654059a3032)

2024-03-20 10:13 UTC, AnnaJ-P11 commented
@bayological This is very strange. I also tested it locally (Google Chrome) and the metamask window appears and I am able to lock it correctly. 
[Screencast from 20-03-24 10:23:58.webm](https://github.com/mento-protocol/governance-ui/assets/153610715/3adcdf2f-328f-4c6d-a5ff-71310f241000)

I also checked it on the Brave browser that you checked on and it also works for me. I don't understand why metamask works so differently.
[Screencast from 20-03-24 11:12:12.webm](https://github.com/mento-protocol/governance-ui/assets/153610715/9b3b384c-29ee-4834-84ee-919445e884eb)

2024-03-29 09:57 UTC, AnnaJ-P11 commented
> @bayological This is very strange. I also tested it locally (Google Chrome) and the metamask window appears and I am able to lock it correctly. [Screencast from 20-03-24 10:23:58.webm](https://github.com/mento-protocol/governance-ui/assets/153610715/3adcdf2f-328f-4c6d-a5ff-71310f241000)
> 
> I also checked it on the Brave browser that you checked on and it also works for me. I don't understand why metamask works so differently. [Screencast from 20-03-24 11:12:12.webm](https://github.com/mento-protocol/governance-ui/assets/153610715/9b3b384c-29ee-4834-84ee-919445e884eb)

2024-03-29 09:57 UTC, closed without merging