feat(51): Extend lock mechanism
mento-protocol/governance-ui pull request #72
Opened 2024-03-08 12:59 UTC by tplocic20

### Description

- Connected the extend button to form and allowed user to extend the lock

### Other changes

- Tiny layout tweaks

### Tested

Go to `My voting power` and select a lock to extend

### Related issues

-  Fixes #51

2024-03-13 11:10 UTC, RyRy79261 commented
@tplocic20 I'm getting an error with `timestamp` being undefined when clicking the `My Voting Power` button. 

I'm using the shared account
![image](https://github.com/mento-protocol/governance-ui/assets/10461622/5a822738-e462-4908-b704-88dc7ba488e8)

2024-03-19 10:22 UTC, chapati23 requested changes
Running into the same issue as @RyRy79261 
<img width="812" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/59de747b-dc11-4fd0-adeb-7a1ddc7dad59">


tested on latest deployment https://governance-925rv5h26-mentolabs.vercel.app/ with this wallet 0x70f2Db6D22593a65Dbb848C94eBACDF0344642F7

2024-03-19 10:49 UTC, AnnaJ-P11 commented
I had the same error, I fixed that on this PR https://github.com/mento-protocol/governance-ui/pull/70/files --> app/components/locks-list/locks-list.component.tsx `const startDate = new Date(lock.lockCreate[0]?.timestamp * 1000);`

2024-03-19 16:34 UTC, chapati23 requested changes
Calendar offers impossible relock dates:

<img width="424" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/b2936f22-e99d-4888-8f11-442ba55ca723">

2024-03-25 11:13 UTC, RyRy79261 commented on app/components/_shared/button/button.component.tsx
> +      className={classNames(block && styles.block, disabled && styles.disabled)}
Can we swap this for tailwind classes 
```suggestion
      className={`${block && "block"} ${disabled && "cursor-not-allowed  pointer-events-none"}`}
```

2024-03-25 11:13 UTC, RyRy79261 commented on app/components/_shared/button/button.module.scss
> +.block {
Redundant

2024-03-25 11:13 UTC, RyRy79261 commented on app/components/_shared/button/button.module.scss
> +  .button {
Redundant

2024-04-22 12:07 UTC, RyRy79261 commented
Closing in favour of #112

2024-04-22 12:07 UTC, closed without merging