Fix-63 proposals design fixes
mento-protocol/governance-ui pull request #78
Opened 2024-03-14 11:26 UTC by AnnaJ-P11

2024-03-14 12:39 UTC, tplocic20 requested changes

2024-03-14 12:39 UTC, tplocic20 commented on app/components/_shared/progress-bar/progress-bar.module.scss
> +  font-family: "Founders Grotesk";
I would move the font definition to the global file

2024-03-14 12:39 UTC, tplocic20 commented on app/globals.scss
> +@font-face {
Shouldn't we be using the Founders Grotesk globally?
So we probably don't need the Inter font

2024-03-14 14:07 UTC, tplocic20 approved these changes

2024-03-19 23:49 UTC, denviljclarke commented on app/components/proposals-list/proposals-list.component.tsx
> +                <Status
The color for the 'Active' status doesn't seem correct.

2024-03-19 23:53 UTC, denviljclarke commented on app/components/proposals-list/proposals-list.component.tsx
>                  <div
The min gap between the progress bar and the title is a bit too small. It's larger in the designs

2024-03-20 00:50 UTC, denviljclarke commented on app/components/_shared/progress-bar/progress-bar.component.tsx
>              <div
Something is causing there to be a small black element between the end of the bar and the container

2024-03-20 00:51 UTC, denviljclarke commented
Nice @AnnaJ-P11. I left a few comments. I also made a commit adding inter using Next.js. I think it's good to use it from there since we already have it installed. 

Also, I see in the designs that there is supposed to be pagination this component, do you know why it's not implemented? 

[Link to pagination in the design](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=8669-3746&mode=design&t=hCDHbnqdmTMkuWFW-4)

2024-03-20 10:28 UTC, AnnaJ-P11 commented
> Nice @AnnaJ-P11. I left a few comments. I also made a commit adding inter using Next.js. I think it's good to use it from there since we already have it installed.
> 
> Also, I see in the designs that there is supposed to be pagination this component, do you know why it's not implemented?
> 
> [Link to pagination in the design](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=8669-3746&mode=design&t=hCDHbnqdmTMkuWFW-4)

Ok, thanks. It looks like pagination has recently been added to the design. I haven't seen it before

2024-03-21 00:05 UTC, denviljclarke approved these changes
I [removed some code](https://github.com/mento-protocol/governance-ui/pull/78/commits/6fc21169b9467b92d7fe98736b9b01414fade0b8) which I introduced in error when testing how a shorter proposal list would look. 

Apart from that note - LGTM 👍

2024-03-21 08:28 UTC, merged