Feat/61 connected chain logic
mento-protocol/governance-ui pull request #81
Opened 2024-03-15 14:51 UTC by AnnaJ-P11

### Description

- add testnet/mainnet text in CELO pill 

### Other changes

- 

### Tested

Go to main page -> Look at CELO pill

### Related issues

-  Fixes #61

2024-03-15 16:36 UTC, tplocic20 approved these changes

2024-03-19 10:53 UTC, nvtaveras requested changes

2024-03-19 10:53 UTC, nvtaveras commented on app/(routes)/page.tsx
> +  const chainText = chain?.testnet ? "Testnet" : "Mainnet";
It looks like you added this but didn't use it anywhere? Also, according to the ticket the pill should read `CELO Mainnet` | `Alfajores Testnet` | `Baklava Testnet`. Not sure if Baklava is still relevant?

2024-03-19 10:58 UTC, AnnaJ-P11 commented on app/(routes)/page.tsx
> +  const chainText = chain?.testnet ? "Testnet" : "Mainnet";
Ohh yes, now I see, I removed chainText from jsx while mrege conficts resolving. I will fix it

2024-03-19 14:07 UTC, nvtaveras commented on app/(routes)/page.tsx
> +  const chainText = chain?.testnet ? "Testnet" : "Mainnet";
Thanks! I think the only thing missing now according to the issue is that when connected to Alfajores it shouldn't say "CELO Testnet" but "Alfajores Testnet" instead, and similar to Baklava

2024-03-19 14:35 UTC, AnnaJ-P11 commented on app/(routes)/page.tsx
> +  const chainText = chain?.testnet ? "Testnet" : "Mainnet";
Baklava Testnet doesn't work for me. When I am at this chain, I console log chain from useAccount and it is 'undefined'.

2024-03-20 12:46 UTC, RyRy79261 commented on app/(routes)/page.tsx
> +  const chainKind = chain?.testnet ? "Testnet" : "Mainnet";
Could use `useMemo` here as the `useAccount` hook might trigger refresh

```suggestion
  const chainKind = useMemo(
    () => (chain?.testnet ? "Testnet" : "Mainnet"),
    [chain?.testnet],
  );
```

2024-03-20 12:46 UTC, RyRy79261 commented on app/(routes)/page.tsx
> +  const chainText = chain?.name || "CELO";
Could use useMemo here as the useAccount hook might trigger refresh
```suggestion
  const chainText = useMemo(
    () => (chain?.name || "CELO"),
    [chain?.name],
  );
```

2024-03-20 12:46 UTC, RyRy79261 commented on app/components/_shared/badge/badge.module.scss
> +  line-height: 18px;
Why is line-height being updated in this context?

Typically line height should be unchanged, if needed potentially using a block element instead

2024-03-20 13:06 UTC, AnnaJ-P11 commented on app/components/_shared/badge/badge.module.scss
> +  line-height: 18px;
I changed that, because designs says that line-height should be the same as font-size

2024-03-21 15:33 UTC, nvtaveras commented on app/(routes)/page.tsx
> +  const chainText = chain?.testnet ? "Testnet" : "Mainnet";
Just tried it on the preview and the name of the networks should be `Celo` and `Alfajores` instead of `CELO`|`ALFAJORES`. This is particularly important for mainnet as `CELO` is used to refer to the asset rather than the network. I updated the ticket to reflect this

2024-03-25 11:19 UTC, RyRy79261 commented on app/components/_shared/badge/badge.module.scss
> +  line-height: 18px;
Could you reference this? Typically you would keep the line hight uniform through out the app and affect positioning only using positioning attributes

2024-03-25 11:29 UTC, nvtaveras commented on app/components/_shared/badge/badge.module.scss
> +  line-height: 18px;
reverted these in https://github.com/mento-protocol/governance-ui/pull/81/commits/9e85f0d22dcecf622671150a6d9fafef3a139f49

let's update this later if needed, while looking at the design I saw some minor differences in the updated version and I believe later on we'll do an app wide check to see how close things are to figma.

2024-03-25 11:32 UTC, nvtaveras approved these changes

2024-03-25 11:42 UTC, nvtaveras approved these changes

2024-03-25 11:42 UTC, merged