Fix/65/59 - Governance params component & title
mento-protocol/governance-ui pull request #82
Opened 2024-03-18 10:09 UTC by tplocic20

### Description

- Updated designs of contract params
- Added mobile version of component
- Changed the logo from svg to the font manipulation

### Other changes

- Couple of tweaks in UI

### Related issues

- Fixes #65 
- Fixes #59

2024-03-18 13:24 UTC, AnnaJ-P11 approved these changes

2024-03-18 23:33 UTC, denviljclarke commented on app/globals.scss
> +  -webkit-text-stroke-width: 1px;
The code I send had 1.2px. Is there a reason why you changed it @tplocic20?

2024-03-18 23:36 UTC, denviljclarke commented on app/(routes)/page.tsx
> -            <div className="flex flex-row justify-start place-items-center gap-x3 font-bold font-size-x6 sm:font-size-x11">
The alignment of the text & the logo is off

2024-03-18 23:56 UTC, denviljclarke commented on app/(routes)/page.tsx
>            <p className="mb-x6 text-x4">Transparent Digital Asset Solutions</p>
This text it supposed to be 22px. I think x4 = 20, if I'm not mistaken.

2024-03-19 00:00 UTC, denviljclarke commented on app/(routes)/page.tsx
> +    <main className="flex flex-col place-items-center mt-x11 font-fg">
Using font-fg here breaks other things. e.g the total supply badge.

2024-03-19 00:18 UTC, denviljclarke commented on app/(routes)/page.tsx
> +      <h2 className="font-size-x6 line-height-x6 mt-x6 font-medium text-center max-w-[17em]">
Text here is too big on mobile.

2024-03-19 00:18 UTC, denviljclarke commented on app/(routes)/page.tsx
> +      <h1 className="font-size-x8 text-center md:font-size-x11 font-bold leading-2 md:leading-loose tracking-wide whitespace-break-spaces">
This is broken on mobile

2024-03-19 00:32 UTC, denviljclarke commented on app/(routes)/page.tsx
>        <Card className="mt-x11" block>
Spacing, font size is off on mobile

2024-03-19 01:07 UTC, denviljclarke commented on app/components/_shared/header/header.component.tsx
> +        <Button theme="link" onClick={() => setDrawerOpened(!drawerOpened)}>
This button is supposed to turn into an x when the menu it open like in the designs. At the moment, it only changes color. We have this header component implemented in the airgrab & the website, so there's not need to recreat it. You can remove the changes for the header from this PR and go ahead with the other changes. I'll create a new PR to migrate the header from our other websites to the Gov UI, I've already started it.

2024-03-19 01:09 UTC, denviljclarke commented on app/components/_shared/header/header.component.tsx
> +        <Button theme="link" onClick={() => setDrawerOpened(!drawerOpened)}>
I thought a bit more & we have this header component implemented in the airdrop site and the website, so there's no need to recreate it. You can remove the header changes from this PR and go ahead with the other changes. I'll create a new PR to migrate the header from our other websites to the Gov UI, I've already started it.

2024-03-19 01:19 UTC, denviljclarke requested changes
Left a few comments about some designs tweaks & the header component

2024-03-19 10:26 UTC, tplocic20 commented on app/globals.scss
> +  -webkit-text-stroke-width: 1px;
Just an oversight

2024-03-19 10:31 UTC, tplocic20 commented on app/(routes)/page.tsx
> -            <div className="flex flex-row justify-start place-items-center gap-x3 font-bold font-size-x6 sm:font-size-x11">
Looks like there is an issue with the font file and the font has some strange built in padding

2024-03-19 23:35 UTC, denviljclarke commented on app/(routes)/page.tsx
>          <Expandable
P in parameters needs to be capitalized & there needs to be some more padding, like the design.

2024-03-19 23:35 UTC, denviljclarke commented on app/(routes)/page.tsx
>                <MentoIcon
This is too large on mobile

2024-03-19 23:39 UTC, denviljclarke commented on app/(routes)/page.tsx
> +        Participate in the governance process of Mento stablecoin platform
I would be good to get the formatting like the design, with the word 'platform' on a new line

2024-03-20 23:54 UTC, denviljclarke commented on app/components/_shared/header/header.component.tsx
> +        <Button theme="link" onClick={() => setDrawerOpened(!drawerOpened)}>
[created an issue for this](https://github.com/mento-protocol/governance-ui/issues/86)

2024-03-25 15:50 UTC, bayological approved these changes
All looks fine, however we need two minor adjustments.

2024-03-25 15:50 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +    <Expandable
One of the points mentioned in [this issue](https://github.com/mento-protocol/governance-ui/issues/65) is that the whole row with the text "Governance Parameters" should be clickable instead of just the arrow. This still needs to be updated.

2024-03-25 15:50 UTC, bayological commented on app/components/contract-params/contract-params.component.tsx
> +      <div
This font-weight of the values in the params need to be adjusted. In [the designs](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=7920-11590&mode=design&t=exvNyHeIH1otPX3N-4), the values have a weight of 400, they are currently 300.

2024-03-26 22:23 UTC, denviljclarke approved these changes

2024-03-26 22:26 UTC, merged