Feat(95): Read functions
mento-protocol/governance-ui pull request #99
Opened 2024-03-27 15:44 UTC by RyRy79261

## Overview 

This PR refactors a lot of the data reads to make access more streamlined, `graphql-codegen` has been used to create the various hooks with wrappers being added to join chain & graph data together.

## Related tickets

- closes #95

2024-03-28 15:28 UTC, denviljclarke commented on src/lib/contracts/locking/useLockingTotalSupply.ts
> +const useLockingTotalSupply = () => {
Like on the FE, I think referring to Locking as veMento is a bit clearer e.g `useVeMentoTotalSupply`

2024-03-28 15:35 UTC, denviljclarke commented on src/lib/contracts/useGetContractsInfo.ts
> +  //   const { data, error: apolloError } = useQuery(GetContractsInfo, {
Do we still need this?

2024-03-28 15:37 UTC, denviljclarke commented on src/lib/graphql/celo-explorer/generated/celoGraph.tsx
> +import { gql } from '@apollo/client';
Was this generated as a tsx file? It feels like it should be .ts

2024-03-28 15:41 UTC, denviljclarke commented on codegen.ts
> +    "./src/lib/graphql/subgraph/generated/subgraph.tsx": {
Ahh, the output file is specified here. Let's change this to .ts. wdyt?

2024-03-28 19:12 UTC, RyRy79261 commented on src/lib/contracts/useGetContractsInfo.ts
> +  //   const { data, error: apolloError } = useQuery(GetContractsInfo, {
Its a read query in used in the app, do you mean the comment?

2024-03-28 19:12 UTC, RyRy79261 commented on src/lib/contracts/locking/useLockingTotalSupply.ts
> +const useLockingTotalSupply = () => {
I've nuked it after the fix PR #102

2024-03-28 20:04 UTC, denviljclarke commented on codegen.ts
> +    "./src/lib/graphql/subgraph/generated/subgraph.tsx": {
Ok np, got it. It just felt weird at a glance 😅

2024-03-28 20:06 UTC, denviljclarke commented on src/lib/contracts/useGetContractsInfo.ts
> +  //   const { data, error: apolloError } = useQuery(GetContractsInfo, {
Yeh, the comment. It seems I selected the wrong line. Looks good now 👍

2024-03-28 20:06 UTC, denviljclarke commented
LGTM 🫡

2024-04-03 10:32 UTC, chapati23 requested changes
Details page is broken for me

2024-04-03 10:32 UTC, chapati23 commented on src/app/(routes)/proposals/[id]/page.tsx
> -import { useMemo } from "react";
Details page is broken for me, somewhere we're trying to serialize a BigInt

https://governance-2esaba9d7-mentolabs.vercel.app/proposals/1788130690851969321761660844276733770864782080735732005121452579323831102760

<img width="500" alt="image" src="https://github.com/mento-protocol/governance-ui/assets/117495/17273654-edb2-4593-9040-d9e0fd43540c">

2024-04-03 19:03 UTC, RyRy79261 commented on src/app/(routes)/proposals/[id]/page.tsx
> -import { useMemo } from "react";
It's broken on dev as well 🤔

2024-04-04 10:40 UTC, chapati23 approved these changes
fixed a small regression with the wrong execution code component being used, now all read functions look good AFAICS!

2024-04-04 11:57 UTC, merged